services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test_root_pass
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - testnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - testnetwork

volumes:
  mysql_data:
  
networks:
  testnetwork:
